import Link from 'next/link';

export default function FIDCDetailsPage() {
  return (
    <div className="container mx-auto p-6 max-w-4xl">
      <nav className="mb-8">
        <Link 
          href="/" 
          className="text-blue-600 hover:text-blue-800 flex items-center"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to Home
        </Link>
      </nav>
      
      <h1 className="text-4xl font-bold mb-6">Understanding FIDC in Detail</h1>
      
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">What is a FIDC?</h2>
        <p className="mb-4">
          A FIDC (Fundo de Investimento em Direitos Creditórios) is a Brazilian investment fund that primarily 
          invests in credit rights. In our blockchain implementation, these funds are tokenized and operate as 
          smart contracts on the blockchain.
        </p>
        <p>
          The FIDC allows companies (payables) to securitize their receivables, while investors can earn yields 
          by providing capital to the fund. This model creates a win-win scenario where businesses get immediate 
          liquidity, and investors get exposure to structured credit investments with attractive yields.
        </p>
      </section>
      
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">Key Participants in the FIDC Ecosystem</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Manager</h3>
            <p>Responsible for setting up the FIDC and defining its parameters (yield rates, fee, grace period). The manager earns a performance fee on the yield generated by the fund.</p>
          </div>
          
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Validator</h3>
            <p>Reviews and approves the FIDC emission, ensuring regulatory compliance and risk assessment of the underlying assets.</p>
          </div>
          
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Payable</h3>
            <p>The company that provides the receivables (credit rights) that serve as collateral for the FIDC. They receive immediate liquidity for their future receivables.</p>
          </div>
          
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Investors</h3>
            <p>Participate by investing capital in the FIDC. There are two types:</p>
            <ul className="list-disc list-inside mt-2">
              <li><strong>Senior Investors:</strong> Lower risk, receive additional yield spread</li>
              <li><strong>Subordinated Investors:</strong> Higher risk, receive base yield only</li>
            </ul>
          </div>
        </div>
      </section>
      
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">FIDC Lifecycle</h2>
        
        <div className="relative">
          {/* Timeline */}
          <div className="absolute h-full w-0.5 bg-gray-200 left-6 md:left-1/2 transform md:-translate-x-0.5"></div>
          
          {/* Steps */}
          <div className="space-y-12 relative">
            {/* Step 1 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 mb-4 md:mb-0 md:text-right">
                <h3 className="text-lg font-semibold">1. Initialization</h3>
                <p>Manager initializes the FIDC with parameters: annual yield, senior spread, manager fee, and grace period.</p>
              </div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">1</div>
              <div className="md:w-1/2 md:pl-8 invisible md:visible"></div>
            </div>
            
            {/* Step 2 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 invisible md:visible"></div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">2</div>
              <div className="md:w-1/2 md:pl-8 mb-4 md:mb-0">
                <h3 className="text-lg font-semibold">2. Validation</h3>
                <p>Validator reviews and approves the FIDC emission, verifying collateral and compliance.</p>
              </div>
            </div>
            
            {/* Step 3 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 mb-4 md:mb-0 md:text-right">
                <h3 className="text-lg font-semibold">3. Collateralization</h3>
                <p>Payable company transfers collateral to the FIDC, activating the fund.</p>
              </div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">3</div>
              <div className="md:w-1/2 md:pl-8 invisible md:visible"></div>
            </div>
            
            {/* Step 4 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 invisible md:visible"></div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">4</div>
              <div className="md:w-1/2 md:pl-8 mb-4 md:mb-0">
                <h3 className="text-lg font-semibold">4. Investor Approval</h3>
                <p>Manager approves senior and subordinated investors to participate in the fund.</p>
              </div>
            </div>
            
            {/* Step 5 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 mb-4 md:mb-0 md:text-right">
                <h3 className="text-lg font-semibold">5. Investment</h3>
                <p>Approved investors deposit capital into the FIDC, receiving quotas in return.</p>
              </div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">5</div>
              <div className="md:w-1/2 md:pl-8 invisible md:visible"></div>
            </div>
            
            {/* Step 6 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 invisible md:visible"></div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">6</div>
              <div className="md:w-1/2 md:pl-8 mb-4 md:mb-0">
                <h3 className="text-lg font-semibold">6. Grace Period</h3>
                <p>Investments must remain in the fund for at least the grace period before redemption.</p>
              </div>
            </div>
            
            {/* Step 7 */}
            <div className="flex flex-col md:flex-row items-center">
              <div className="md:w-1/2 md:pr-8 mb-4 md:mb-0 md:text-right">
                <h3 className="text-lg font-semibold">7. Redemption</h3>
                <p>After grace period, investors can redeem their principal plus accrued yield.</p>
              </div>
              <div className="bg-blue-500 rounded-full h-12 w-12 flex items-center justify-center text-white font-bold z-10">7</div>
              <div className="md:w-1/2 md:pl-8 invisible md:visible"></div>
            </div>
          </div>
        </div>
      </section>
      
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">Yield Calculation in Detail</h2>
        
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 mb-6">
          <h3 className="text-xl font-medium mb-4">Formula</h3>
          
          <div className="mb-6">
            <p className="font-mono text-lg mb-2">Yield = Principal × Annual Rate × Time</p>
            <p>Where:</p>
            <ul className="list-disc list-inside mt-2">
              <li><strong>Principal:</strong> Amount invested in DREX tokens</li>
              <li><strong>Annual Rate:</strong> Base yield (for subordinated) or base yield + spread (for senior)</li>
              <li><strong>Time:</strong> Investment duration in years (capped at 3 years maximum)</li>
            </ul>
          </div>
          
          <h3 className="text-xl font-medium mb-4">Manager Fee</h3>
          <p className="mb-2">The manager fee is calculated as a percentage of the gross yield:</p>
          <p className="font-mono mb-4">Manager Fee = Gross Yield × Fee Rate</p>
          
          <h3 className="text-xl font-medium mb-4">Net Yield</h3>
          <p className="mb-2">The net yield paid to investors is:</p>
          <p className="font-mono mb-4">Net Yield = Gross Yield - Manager Fee</p>
          
          <h3 className="text-xl font-medium mb-4">Total Repayment</h3>
          <p className="mb-2">The total amount repaid to investors on redemption:</p>
          <p className="font-mono">Total Repayment = Principal + Net Yield</p>
        </div>
        
        <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-6">
          <h3 className="text-xl font-medium mb-4">Example Calculation</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold mb-2">Input Parameters</h4>
              <ul className="space-y-2">
                <li><strong>Principal:</strong> 1,000 DREX</li>
                <li><strong>Annual Yield:</strong> 15% (1500 BPS)</li>
                <li><strong>Senior Spread:</strong> 5% (500 BPS)</li>
                <li><strong>Manager Fee:</strong> 2% (200 BPS)</li>
                <li><strong>Investment Duration:</strong> 6 months (0.5 years)</li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-semibold mb-2">For Senior Investor</h4>
              <ul className="space-y-1">
                <li>Annual Rate = 15% + 5% = 20%</li>
                <li>Gross Yield = 1,000 × 20% × 0.5 = 100 DREX</li>
                <li>Manager Fee = 100 × 2% = 2 DREX</li>
                <li>Net Yield = 100 - 2 = 98 DREX</li>
                <li>Total Repayment = 1,000 + 98 = 1,098 DREX</li>
              </ul>
              
              <h4 className="font-semibold mt-4 mb-2">For Subordinated Investor</h4>
              <ul className="space-y-1">
                <li>Annual Rate = 15% (no spread)</li>
                <li>Gross Yield = 1,000 × 15% × 0.5 = 75 DREX</li>
                <li>Manager Fee = 75 × 2% = 1.5 DREX</li>
                <li>Net Yield = 75 - 1.5 = 73.5 DREX</li>
                <li>Total Repayment = 1,000 + 73.5 = 1,073.5 DREX</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">Key Limitations and Safeguards</h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Grace Period</h3>
            <p className="mb-2">Minimum: 1 day</p>
            <p>Maximum: 365 days</p>
            <p className="mt-2">This prevents immediate redemptions and ensures stability of the fund.</p>
          </div>
          
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Maximum Yield Calculation Time</h3>
            <p>Capped at 3 years (1095 days)</p>
            <p className="mt-2">Even if an investment is held longer, yield will only be calculated for a maximum of 3 years.</p>
          </div>
          
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Senior Ratio</h3>
            <p>Minimum: 50% senior investment</p>
            <p className="mt-2">At least half of the total investment must come from senior investors, ensuring proper risk distribution.</p>
          </div>
          
          <div className="p-4 border rounded-lg">
            <h3 className="text-lg font-medium mb-2">Maximum Senior Spread</h3>
            <p>Capped at 20% (2000 BPS)</p>
            <p className="mt-2">This limits the maximum additional yield that can be given to senior investors.</p>
          </div>
        </div>
      </section>
      
      <div className="mt-10 text-center">
        <Link 
          href="/fidc-demo" 
          className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors inline-block"
        >
          Try the FIDC Flow Demo
        </Link>
      </div>
    </div>
  );
} 