/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Collateral__factory } from "./Collateral__factory";
export { Erc20__factory } from "./Erc20__factory";
export { Fidc__factory } from "./Fidc__factory";
