/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Collateral } from "./Collateral";
export type { Erc20 } from "./Erc20";
export type { Fidc } from "./Fidc";
export * as factories from "./factories";
export { Collateral__factory } from "./factories/Collateral__factory";
export { Erc20__factory } from "./factories/Erc20__factory";
export { Fidc__factory } from "./factories/Fidc__factory";
